# Generated by Django 3.1.2 on 2020-10-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pollution_station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'pollution_stations',
            },
        ),
    ]
