# Generated by Django 3.1.3 on 2020-12-06 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password1',
            field=models.CharField(default=django.utils.timezone.now, help_text='Minimum 8 characters.', max_length=60),
            preserve_default=False,
        ),
    ]
