# Generated by Django 3.1.3 on 2020-12-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password1',
        ),
    ]
