# Generated by Django 3.1.2 on 2020-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_ip', models.GenericIPAddressField()),
                ('station_port', models.IntegerField()),
                ('station_adding_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
