# Generated by Django 3.1.2 on 2020-11-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0002_custom_station'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom_station',
            options={'verbose_name': 'station', 'verbose_name_plural': 'stations'},
        ),
    ]
