# Generated by Django 3.1.2 on 2020-11-24 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pollution', '0004_auto_20201122_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_station',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stations', to=settings.AUTH_USER_MODEL),
        ),
    ]
