# Generated by Django 3.1.3 on 2020-11-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0006_auto_20201129_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_station',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
